### ISSUE TITLE
[Bug] Doesnt work with multi monitor

### ISSUE THREAD

**Issue by SvenBent** [henrypp/freeshooter#41] opened 2023-12-03 22:44 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

2.0.7

### Windows version

Windows &

### Steps to reproduce

1: move mouse cursors to any screen that is not main screen
2: click the hotkey to take a screenshoot : region
3: notice it wont allowed you to select and areas on this none main monitor

### Expected behavior

Allowed me to select and area that it would screenshoot

### Actual behavior

did not allow me to select a region to screenshoot

**Comment by henrypp** [comment] 2023-12-04 09:35
it maybe duplicate of #31 and now it is fixed, im not releasing new version for 5 years, lol

**Closed as completed by henrypp** 2023-12-04 09:35 UTC
Labels: bug
